### ISSUE TITLE
where to get the datasets used in the exp

### ISSUE THREAD

**Issue by Lizeerd** [AuthorXXX/Learning-Recurrent-Binary-Ternary-Weights#1]
hi, i'm trying to run ur code, but have no idea where can i find the npz form of those datasets

**Comment by DanyEle** [comment]
For the experiments on the MNIST dataset, you need to install and configure fuel then do:

```
fuel-download mnist
fuel-convert mnist
```

For further info on how to install Fuel, refer to: https://fuel.readthedocs.io/en/latest/setup.html

I'll let you know if I manage to get the other experiments running!

**Comment by ElijahBele** [comment]
> For the experiments on the MNIST dataset, you need to install and configure fuel then do:
> 
> ```
> fuel-download mnist
> fuel-convert mnist
> ```
> 
> For further info on how to install Fuel, refer to: https://fuel.readthedocs.io/en/latest/setup.html
> 
> I'll let you know if I manage to get the other experiments running!

Hi, Do you manage to get the other experiments running?
I cannot find the char-level War and Peace npz.

**Comment by DanyEle** [comment]
Yeah, I managed to get all the experiments running, though I had to fiddle with the data loading part a bit. Here is the char-level War and Peace npz. I can't remember exactly where I downloaded it from though as some months have past now. Probably the fuel repository?


[CHAR_LEVEL_WAR_AND_PEACE.zip](https://github.com/arashardakani/Learning-Recurrent-Binary-Ternary-Weights/files/3554683/CHAR_LEVEL_WAR_AND_PEACE.zip)

**Comment by ElijahBele** [comment]
Thanks a lot!

**Comment by Jvafaei** [comment]
> For the experiments on the MNIST dataset, you need to install and configure fuel then do:
> 
> ```
> fuel-download mnist
> fuel-convert mnist
> ```
> 
> For further info on how to install Fuel, refer to: https://fuel.readthedocs.io/en/latest/setup.html
> 
> I'll let you know if I manage to get the other experiments running!

Hi,I am trying to run sMNIST on google colab, but I get this error : 

> `Preparing the dataset
Traceback (most recent call last):
  File "sMNIST.py", line 68, in <module>
    train_set = get_stream(which_set="train", batch_size=batch_size)
  File "/content/drive/My Drive/Colab Notebooks/ardakani/sMNIST/reader.py", line 43, in get_stream
    dataset = get_dataset(which_set)
  File "/content/drive/My Drive/Colab Notebooks/ardakani/sMNIST/reader.py", line 37, in get_dataset
    train=MNIST(which_sets=["train"], subset=slice(None, 50000)),
  File "/usr/local/lib/python3.6/dist-packages/fuel/datasets/mnist.py", line 32, in __init__
    file_or_path=find_in_data_path(self.filename),
  File "/usr/local/lib/python3.6/dist-packages/fuel/utils/__init__.py", line 429, in find_in_data_path
    for path in config.data_path:
  File "/usr/local/lib/python3.6/dist-packages/fuel/config_parser.py", line 150, in __getattr__
    "provided: {}.".format(key))
fuel.exceptions.ConfigurationError: Configuration not set and no default provided: data_path.
[2efbd358fa79:01003] *** Process received signal ***
[2efbd358fa79:01003] Signal: Segmentation fault (11)
[2efbd358fa79:01003] Signal code: Address not mapped (1)
[2efbd358fa79:01003] Failing at address: 0x7f49fd85920d
[2efbd358fa79:01003] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7f4a00503890]
[2efbd358fa79:01003] [ 1] /lib/x86_64-linux-gnu/libc.so.6(getenv+0xa5)[0x7f4a00142785]
[2efbd358fa79:01003] [ 2] /usr/lib/x86_64-linux-gnu/libtcmalloc.so.4(_ZN13TCMallocGuardD1Ev+0x34)[0x7f4a009ade44]
[2efbd358fa79:01003] [ 3] /lib/x86_64-linux-gnu/libc.so.6(__cxa_finalize+0xf5)[0x7f4a00143615]
[2efbd358fa79:01003] [ 4] /usr/lib/x86_64-linux-gnu/libtcmalloc.so.4(+0x13cb3)[0x7f4a009abcb3]
[2efbd358fa79:01003] *** End of error message ***`
